services:
  php-app:
    build: .
    ports:
      - "9090:80"
    depends_on:
      - mysql-db
    volumes:
      - uploads_data:/var/www/html/uploads

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  uploads_data: